name: solarnet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - jupyter
  - scipy
  - pandas
  - netcdf4
  - bqplot
  - pyevtk
  - sunpy=2.0.6
  - heliopy=0.15.2
  - ndcube=1.4.2
  - pip:
    - cdflib==0.3.19
    - git+https://gitlab.com/snowwattle/irispy-lmsal.git@5121196b4b27b59b04031c99179a20bc79a24fdf
    - git+https://github.com/tiagopereira/sunraster.git@a54c1031a9bf9ac31dd0a0aeebe7634b2ace211a
