name: solarnet
channels:
  - conda-forge
  - defaults
dependencies:
  - sunpy=2.0.6
  - heliopy=0.15.2
  - ndcube=1.4.2
  - sunraster=0.1.2
  - jupyter
  - jupyterlab
  - pip
  - pip:
    - cdflib==0.3.19
    - git+https://gitlab.com/LMSAL_HUB/iris_hub/irispy-lmsal.git@3a0f2af37403cb6a25e7cb2780b1377c207817b4
